In [13]:
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

display(books)

display(books.isna())

display(books.describe())

books['revenue'] = books['price'] * books['units_sold']
display(books['revenue'].sum())

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

   title  author  genre  price  units_sold  in_stock
0  False   False  False  False       False     False
1  False   False  False  False       False     False
2  False   False  False  False       False     False
3  False   False  False  False       False     False
4  False   False  False  False       False     False

           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.000000
std     9.232715   54.359912
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  120.000000
max    55.000000  200.000000

21834.3

In [14]:
books['revenue'] = books['price'] * books['units_sold']
print(books.info())
print(books.describe())
print(f"Total revenue: £{books['revenue'].sum():,.2f}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
 6   revenue     5 non-null      float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 373.0+ bytes
None
           price  units_sold      revenue
count   5.000000    5.000000     5.000000
mean   42.296000  111.000000  4366.860000
std     9.232715   54.359912  1288.674939
min    29.990000   60.000000  3300.000000
25%    38.500000   80.000000  3360.000000
50%    42.000000   95.000000  3657.500000
75%    45.990000  120.000000  5518.800000
max    55.000000  200.000000  5998.000000
Total revenue: £21,834.30

In [20]:
display(books.loc[:, ["title", "revenue"]])

                           title  revenue
0       The Pragmatic Programmer   5518.8
1                     Clean Code   3657.5
2            Python Crash Course   5998.0
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

In [28]:
display(books.iloc[-3:, :3])

premium_stock = books.loc[(books['in_stock'] == True) & (books['price'] >40)]
display(premium_stock)

top_book = books.loc[books['units_sold'].idxmax()]
print(top_book)

print(f"Top earner: {top_book['title']} with revenue of £{top_book['revenue']:,.2f}")

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object
Top earner: Python Crash Course with revenue of £5,998.00

In [35]:
def get_tier(price):
    if price <35:
        return 'Budget'
    elif price <= 50:
        return 'Standard'
    else:
        return 'Premium'

books['price_tier'] = books['price'].apply(get_tier)

books_sorted = books.sort_values('revenue', ascending = False)
display(books)

books['sales_rank'] = books['units_sold'].rank(ascending=False).astype(int)
display(books)

books['genre_encoded'] = books['genre'].map({'Tech':0,'Data':1})

print(books[['title','price_tier','sales_rank','genre_encoded']])

,title,author,genre,price,units_sold,in_stock,revenue,sales_rank,genre_encoded,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,2,0,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,3,0,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,1,0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,4,1,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,5,1,Premium

,title,author,genre,price,units_sold,in_stock,revenue,sales_rank,genre_encoded,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,2,0,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,3,0,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,1,0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,4,1,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,5,1,Premium

                           title price_tier  sales_rank  genre_encoded
0       The Pragmatic Programmer   Standard           2              0
1                     Clean Code   Standard           3              0
2            Python Crash Course     Budget           1              0
3      Data Science from Scratch   Standard           4              1
4  Designing Data-Intensive Apps    Premium           5              1